{ config, pkgs, ... }:

{
  # Imports hardware definitions generated by the installer
  imports = [ ./hardware-configuration.nix ];

  # --- Bootloader ---
  # Use systemd-boot as the EFI boot manager (standard for modern NixOS installs)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # --- Networking ---
  networking.hostName = "nixos-pc"; # Define your hostname
  networking.networkmanager.enable = true; # Enable NetworkManager for wireless/wired connections

  # --- Time & Locale ---
  time.timeZone = "America/New_York";
  
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # --- Desktop Environment (Optional) ---
  # Uncomment the following lines if you want to use the GNOME desktop
  # services.xserver.enable = true;
  # services.xserver.displayManager.gdm.enable = true;
  # services.xserver.desktopManager.gnome.enable = true;

  # --- User Management ---
  # Define a user account and give them sudo privileges (wheel)
  users.users.myuser = {
    isNormalUser = true;
    description = "My Username";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
      firefox
      git
      vim
    ];
  };

  # --- Package Management & Environment ---
  nixpkgs.config.allowUnfree = true; # Allow proprietary/unfree packages

  # List packages installed in system profile (available to all users)
  environment.systemPackages = with pkgs; [
    wget
    curl
  ];

  # --- OpenSSH (Optional) ---
  # services.openssh.enable = true;

  # --- System State Version ---
  # DO NOT change this without reading the NixOS release notes for your version
  system.stateVersion = "24.05";
}
