name: End-to-End Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -f ci/Dockerfile -t ninjection-test .

      - name: Run End-to-End Tests in Container
        run: |
          mkdir -p debug
          touch debug/debug_log.txt
          docker run --rm \
            -v ${{ github.workspace }}/debug:/debug \
            ninjection-test
        continue-on-error: true

      - name: Find lua_ls.lua
        run: find /nix/store -type f -name "lua_ls.lua"

      - name: Dump debug log
        run: cat debug/debug_log.txt || echo "No debug log written"
