name: End-to-End Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -f ci/Dockerfile -t ninjection-test .

      - name: Run End-to-End Tests in Container
        run: |
          docker run --rm ninjection-test | tee test_output.log

          echo "========== TEST SUMMARY =========="
          grep -E "Success:|Failed :|Errors :" test_output.log || echo "No summary found in output"
          if grep -qE "Failed\s*:\s*[1-9]|Errors\s*:\s*[1-9]" test_output.log; then
          echo "Some tests failed ❌"
            exit 1
          else
            echo "All tests passed ✅"
          fi
        continue-on-error: true
