name: End-to-End Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Absorb submodule Git directories
        run: git submodule absorbgitdirs

      # Restore the cached Nix store closure tarball if available.
      - name: Restore Nix Store Closure Cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: .ci/nix-store-closure.tar.gz
          key: ${{ runner.os }}-nix-store-closure-${{ hashFiles('ci/nix/kickstart-nix.nvim/**') }}

      - name: Build Docker Image
        run: |
          docker build -f ci/Dockerfile -t ninjection-test .

      - name: Save Nix Store Closure Cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: .ci/nix-store-closure.tar.gz
          key: ${{ runner.os }}-nix-store-closure-${{ hashFiles('ci/nix/kickstart-nix.nvim/**') }}

      - name: Run End-to-End Tests in Container
        run: docker run --rm ninjection-test
