name: Ninjection E2E Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-22.04
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        id: build
        run: |
          docker build -f ci/Dockerfile -t ninjection-test .

  health-tests:
    needs: build-image
    runs-on: ubuntu-22.04
    steps:
      - name: Run health tests
        run: |
          docker run --rm ninjection-test nvim-dev --headless -c "PlenaryBustedDirectory tests/health" -c "qa"

  nix-lua-tests:
    needs: build-image
    runs-on: ubuntu-22.04
    steps:
      - name: Run nix-lua tests
        run: |
          docker run --rm ninjection-test nvim-dev --headless -c "PlenaryBustedDirectory tests/ft/nix/lua" -c "qa"

  lua-nix-tests:
    needs: build-image
    runs-on: ubuntu-22.04
    steps:
      - name: Run lua-nix tests
        run: |
          docker run --rm ninjection-test nvim-dev --headless -c "PlenaryBustedDirectory tests/ft/lua/nix" -c "qa"
