---
name: Luacheck Linting Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: date +%F > todays-date

      - name: Restore cache for Luacheck
        uses: actions/cache@v3
        with:
          path: .ci/luacheck
          key: luacheck-${{ hashFiles('todays-date') }}

      - name: Install Lua and Luarocks
        run: |
          sudo apt update
          sudo apt install -y lua5.1 luarocks

      - name: Prepare Luacheck
        run: |
          test -d .ci/luacheck || {
            mkdir -p .ci/luacheck
            git clone https://github.com/mpeterv/luacheck.git .ci/luacheck/src
            luarocks --tree=${PWD}/.ci/luacheck make .ci/luacheck/src
          }

      - name: Verify Installation
        run: |
          echo "Luacheck installed in:"
          find ${PWD}/.ci/luacheck -name "luacheck" -type f || echo "Luacheck not found"
          ls -la ${PWD}/.ci/luacheck/bin || echo "No binaries found in .ci/luacheck/bin"
          ls -la ${PWD}/.ci/luacheck/src/bin || echo "No binaries found in .ci/luacheck/src/bin"

      - name: Run Luacheck
        run: |
          export PATH="${PWD}/.ci/luacheck/src/bin:${HOME}/.luarocks/bin:${PATH}"
          export LUA_PATH="${PWD}/.ci/luacheck/share/lua/5.1/?.lua;;"
          export LUA_CPATH="${PWD}/.ci/luacheck/lib/lua/5.1/?.so;;"
          echo "PATH is $PATH"
          echo "LUA_PATH is $LUA_PATH"
          lua ${PWD}/.ci/luacheck/src/bin/luacheck.lua --version
          lua ${PWD}/.ci/luacheck/src/bin/luacheck.lua .
