---
name: Luacheck Linting Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: date +%F > todays-date

      - name: Restore cache for Luacheck
        uses: actions/cache@v3
        with:
          path: .ci/luacheck
          key: luacheck-${{ hashFiles('todays-date') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks build-essential

      - name: Prepare Luacheck
        run: |
          test -d .ci/luacheck || {
            mkdir -p .ci/luacheck
            git clone https://github.com/mpeterv/luacheck.git .ci/luacheck/src
            cd .ci/luacheck/src
            luarocks make
            ln -s $(luarocks which luacheck) ../../luacheck/luacheck
          }

      - name: Run Luacheck
        run: |
          export PATH="${PWD}/.ci/luacheck:${PATH}"
          luacheck --version
          make -f ci/Makefile luacheck
