---
name: Linting

on: [push, pull_request, workflow_dispatch]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - name: Run check
        run: |
          export PATH="${PWD}/.ci/neovim/bin:${PATH}"
          export PATH="${PWD}/.ci/lua-ls/bin:${PATH}"
          export VIMRUNTIME="${PWD}/.ci/neovim/share/nvim/runtime"
          make -f ci/Makefile luacheck
