---
name: Luacheck Linting Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: "./lua ./plugin"
