name: Style checking

on: [push, pull_request, workflow_dispatch]

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-22.04
    steps:
      - name: Run check
        run: |
          export PATH="${PWD}/.ci/neovim/bin:${PATH}"
          export PATH="${PWD}/.ci/lua-ls/bin:${PATH}"
          export VIMRUNTIME="${PWD}/.ci/neovim/share/nvim/runtime"
          nvim --version
          make -f ci/Makefile stylua
