---
name: Type Check Lua Code Base
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Type Check Lua Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Type Check Lua Code Base
        uses: mrcjkb/lua-typecheck-action@v0
