---
name: Type Check Code Base
on:
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout dependency neovim runtime treesitter
        uses: actions/checkout@v3
        with:
          repository: "folke/lazydev.nvim"
          path: "deps/lazydev.nvim"

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v1
        with:
          directories: |
            lua
          configpath: ".github/workflows/.luarc.json"
